/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.asus;

public class openni2FrameListener extends VideoStream.NewFrameListener {
  private transient long swigCPtr;

  protected openni2FrameListener(long cPtr, boolean cMemoryOwn) {
    super(UnixJNI.openni2FrameListener_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(openni2FrameListener obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UnixJNI.delete_openni2FrameListener(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public openni2FrameListener(SWIGTYPE_p_boost__interprocess__interprocess_semaphore syncSem) {
    this(UnixJNI.new_openni2FrameListener__SWIG_0(SWIGTYPE_p_boost__interprocess__interprocess_semaphore.getCPtr(syncSem)), true);
  }

  public openni2FrameListener() {
    this(UnixJNI.new_openni2FrameListener__SWIG_1(), true);
  }

  public void onNewFrame(VideoStream stream) {
    UnixJNI.openni2FrameListener_onNewFrame(swigCPtr, this, VideoStream.getCPtr(stream), stream);
  }

  public void setCallback(SWIGTYPE_p_boost__functionT_void_fopenni__VideoFrameRef_RF_t callback) {
    UnixJNI.openni2FrameListener_setCallback(swigCPtr, this, SWIGTYPE_p_boost__functionT_void_fopenni__VideoFrameRef_RF_t.getCPtr(callback));
  }

  public void clearCallback() {
    UnixJNI.openni2FrameListener_clearCallback(swigCPtr, this);
  }

  public void enableSyncPro() {
    UnixJNI.openni2FrameListener_enableSyncPro(swigCPtr, this);
  }

}
