/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.asus;

public class openni2DeviceManager {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected openni2DeviceManager(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(openni2DeviceManager obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UnixJNI.delete_openni2DeviceManager(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static SWIGTYPE_p_boost__shared_ptrT_openni2DeviceManager_t getInstance() {
    return new SWIGTYPE_p_boost__shared_ptrT_openni2DeviceManager_t(UnixJNI.openni2DeviceManager_getInstance(), true);
  }

  public static void destroy() {
    UnixJNI.openni2DeviceManager_destroy();
  }

  public boolean init() {
    return UnixJNI.openni2DeviceManager_init(swigCPtr, this);
  }

  public void deInit() {
    UnixJNI.openni2DeviceManager_deInit(swigCPtr, this);
  }

  public void setResolution(int x, int y) {
    UnixJNI.openni2DeviceManager_setResolution(swigCPtr, this, x, y);
  }

  public void getResolution(SWIGTYPE_p_int x, SWIGTYPE_p_int y) {
    UnixJNI.openni2DeviceManager_getResolution(swigCPtr, this, SWIGTYPE_p_int.getCPtr(x), SWIGTYPE_p_int.getCPtr(y));
  }

  public boolean enableIRStream() {
    return UnixJNI.openni2DeviceManager_enableIRStream(swigCPtr, this);
  }

  public boolean enableColorStream() {
    return UnixJNI.openni2DeviceManager_enableColorStream(swigCPtr, this);
  }

  public boolean enableDepthStream() {
    return UnixJNI.openni2DeviceManager_enableDepthStream(swigCPtr, this);
  }

  public void disableIRStream() {
    UnixJNI.openni2DeviceManager_disableIRStream(swigCPtr, this);
  }

  public void disableColorStream() {
    UnixJNI.openni2DeviceManager_disableColorStream(swigCPtr, this);
  }

  public void disableDepthStream() {
    UnixJNI.openni2DeviceManager_disableDepthStream(swigCPtr, this);
  }

  public boolean isIRStreamStarted() {
    return UnixJNI.openni2DeviceManager_isIRStreamStarted(swigCPtr, this);
  }

  public boolean isColorStreamStarted() {
    return UnixJNI.openni2DeviceManager_isColorStreamStarted(swigCPtr, this);
  }

  public boolean isDepthStreamStarted() {
    return UnixJNI.openni2DeviceManager_isDepthStreamStarted(swigCPtr, this);
  }

  public boolean getOneFrame(SWIGTYPE_p_unsigned_char oneFrame) {
    return UnixJNI.openni2DeviceManager_getOneFrame(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(oneFrame));
  }

  public void setColorFrameDataCallback(SWIGTYPE_p_boost__functionT_void_funsigned_char_const_p_int_const_int_const_int_constF_t cb) {
    UnixJNI.openni2DeviceManager_setColorFrameDataCallback(swigCPtr, this, SWIGTYPE_p_boost__functionT_void_funsigned_char_const_p_int_const_int_const_int_constF_t.getCPtr(cb));
  }

  public void clearColorFrameDataCallback() {
    UnixJNI.openni2DeviceManager_clearColorFrameDataCallback(swigCPtr, this);
  }

}
