/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.asus;

public class UnixJNI {
  public final static native long new_VideoStream_NewFrameListener();
  public final static native void delete_VideoStream_NewFrameListener(long jarg1);
  public final static native long new_VideoStream();
  public final static native void delete_VideoStream(long jarg1);
  public final static native long new_openni2FrameListener__SWIG_0(long jarg1);
  public final static native long new_openni2FrameListener__SWIG_1();
  public final static native void delete_openni2FrameListener(long jarg1);
  public final static native void openni2FrameListener_onNewFrame(long jarg1, openni2FrameListener jarg1_, long jarg2, VideoStream jarg2_);
  public final static native void openni2FrameListener_setCallback(long jarg1, openni2FrameListener jarg1_, long jarg2);
  public final static native void openni2FrameListener_clearCallback(long jarg1, openni2FrameListener jarg1_);
  public final static native void openni2FrameListener_enableSyncPro(long jarg1, openni2FrameListener jarg1_);
  public final static native void delete_openni2Device(long jarg1);
  public final static native boolean openni2Device_init(long jarg1, openni2Device jarg1_);
  public final static native void openni2Device_deInit(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_isValid(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_hasIRSensor(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_hasColorSensor(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_hasDepthSensor(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_isImageRegistrationModeSupported(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_setDepthColorSync(long jarg1, openni2Device jarg1_, boolean jarg2);
  public final static native boolean openni2Device_setImageRegistrationMode(long jarg1, openni2Device jarg1_, boolean jarg2);
  public final static native boolean openni2Device_setIRVideoMode(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native boolean openni2Device_setColorVideoMode(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native boolean openni2Device_setDepthVideoMode(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native boolean openni2Device_getIRVideoMode(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native boolean openni2Device_getColorVideoMode(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native boolean openni2Device_getDepthVideoMode(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native boolean openni2Device_setAutoWhiteBalance(long jarg1, openni2Device jarg1_, boolean jarg2);
  public final static native boolean openni2Device_setAutoExposure(long jarg1, openni2Device jarg1_, boolean jarg2);
  public final static native boolean openni2Device_setExposure(long jarg1, openni2Device jarg1_, int jarg2);
  public final static native boolean openni2Device_setGain(long jarg1, openni2Device jarg1_, int jarg2);
  public final static native void openni2Device_setIRFrameCallback(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native void openni2Device_setColorFrameCallback(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native void openni2Device_setDepthFrameCallback(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native boolean openni2Device_startIRStream(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_startColorStream(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_startDepthStream(long jarg1, openni2Device jarg1_);
  public final static native void openni2Device_stopIRStream(long jarg1, openni2Device jarg1_);
  public final static native void openni2Device_stopColorStream(long jarg1, openni2Device jarg1_);
  public final static native void openni2Device_stopDepthStream(long jarg1, openni2Device jarg1_);
  public final static native void openni2Device_stopAllStream(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_isIRStreamStarted(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_isColorStreamStarted(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_isDepthStreamStarted(long jarg1, openni2Device jarg1_);
  public final static native boolean openni2Device_syncGetFrame(long jarg1, openni2Device jarg1_, long jarg2);
  public final static native long openni2DeviceManager_getInstance();
  public final static native void openni2DeviceManager_destroy();
  public final static native void delete_openni2DeviceManager(long jarg1);
  public final static native boolean openni2DeviceManager_init(long jarg1, openni2DeviceManager jarg1_);
  public final static native void openni2DeviceManager_deInit(long jarg1, openni2DeviceManager jarg1_);
  public final static native void openni2DeviceManager_setResolution(long jarg1, openni2DeviceManager jarg1_, int jarg2, int jarg3);
  public final static native void openni2DeviceManager_getResolution(long jarg1, openni2DeviceManager jarg1_, long jarg2, long jarg3);
  public final static native boolean openni2DeviceManager_enableIRStream(long jarg1, openni2DeviceManager jarg1_);
  public final static native boolean openni2DeviceManager_enableColorStream(long jarg1, openni2DeviceManager jarg1_);
  public final static native boolean openni2DeviceManager_enableDepthStream(long jarg1, openni2DeviceManager jarg1_);
  public final static native void openni2DeviceManager_disableIRStream(long jarg1, openni2DeviceManager jarg1_);
  public final static native void openni2DeviceManager_disableColorStream(long jarg1, openni2DeviceManager jarg1_);
  public final static native void openni2DeviceManager_disableDepthStream(long jarg1, openni2DeviceManager jarg1_);
  public final static native boolean openni2DeviceManager_isIRStreamStarted(long jarg1, openni2DeviceManager jarg1_);
  public final static native boolean openni2DeviceManager_isColorStreamStarted(long jarg1, openni2DeviceManager jarg1_);
  public final static native boolean openni2DeviceManager_isDepthStreamStarted(long jarg1, openni2DeviceManager jarg1_);
  public final static native boolean openni2DeviceManager_getOneFrame(long jarg1, openni2DeviceManager jarg1_, long jarg2);
  public final static native void openni2DeviceManager_setColorFrameDataCallback(long jarg1, openni2DeviceManager jarg1_, long jarg2);
  public final static native void openni2DeviceManager_clearColorFrameDataCallback(long jarg1, openni2DeviceManager jarg1_);
  public final static native long openni2FrameListener_SWIGUpcast(long jarg1);
}
