/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.example.asus;

public class VideoStream {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected VideoStream(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(VideoStream obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        UnixJNI.delete_VideoStream(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  static public class NewFrameListener {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected NewFrameListener(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(NewFrameListener obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          UnixJNI.delete_VideoStream_NewFrameListener(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
    public NewFrameListener() {
      this(UnixJNI.new_VideoStream_NewFrameListener(), true);
    }
  
  }

  public VideoStream() {
    this(UnixJNI.new_VideoStream(), true);
  }

}
