/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xiaoi_app_testjni_two_JniMeasurement */

#ifndef _Included_com_xiaoi_app_testjni_two_JniMeasurement
#define _Included_com_xiaoi_app_testjni_two_JniMeasurement
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xiaoi_app_testjni_two_JniMeasurement
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_xiaoi_app_testjni_1two_JniMeasurement_getString
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
